/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ERC6551Registry,
  ERC6551RegistryInterface,
} from "../../contracts/ERC6551Registry";

const _abi = [
  {
    inputs: [],
    name: "InitializationFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "AccountCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "account",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "createAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346015576102b4908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c8063246a00211461005857638a54c52f1461002f575f80fd5b602061004661003d36610087565b939290926100c9565b6040516001600160a01b039091168152f35b3461008357602061004661007761006e36610087565b918395946101a7565b83815191012090610254565b5f80fd5b60a0906003190112610083576004356001600160a01b0381168103610083579060243590604435906064356001600160a01b0381168103610083579060843590565b9390936100d985838686856101a7565b928351946100ed6020860196872088610254565b91823b61016657604080516001600160a01b039485168152602081018a90529081019190915290821692909116907f77a6e51acdcdd8fb360052caa24a303002a4005b1528166bfd71c1b1a2036a8d90606090a4519034f56001600160a01b038116156101575790565b630337323560e31b5f5260045ffd5b505094505050505090565b90601f8019910116810190811067ffffffffffffffff82111761019357604052565b634e487b7160e01b5f52604160045260245ffd5b9093610251936057936040519660208801938452604088015260018060a01b031660608701526080860152608085526101e160a086610171565b604051948592733d60ad80600a3d3981f3363d3d373d3d3d363d7360601b60208501526bffffffffffffffffffffffff199060601b1660348401526e5af43d82803e903d91602b57fd5bf360881b60488401525180918484015e81015f838201520301601f198101835282610171565b90565b90600b9160405191604083015260208201523081520160ff8153605590206001600160a01b03169056fea26469706673582212206fde6e82bb0dfd67b73ea8c1e1c2cb3755b0b7c4c6563db96bac0183a02c151264736f6c634300081a0033";

type ERC6551RegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC6551RegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC6551Registry__factory extends ContractFactory {
  constructor(...args: ERC6551RegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERC6551Registry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC6551Registry__factory {
    return super.connect(runner) as ERC6551Registry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC6551RegistryInterface {
    return new Interface(_abi) as ERC6551RegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC6551Registry {
    return new Contract(address, _abi, runner) as unknown as ERC6551Registry;
  }
}
